services:
  test:
    image: buildkite/plugin-tester:latest
    volumes:
      - $PWD:/plugin

  format-shell:
    image: mvdan/shfmt
    volumes:
      - $PWD:/data
    command:
      - --write
      - ./data

  lint-shell-format:
    image: mvdan/shfmt
    volumes:
      - $PWD:/data
    command:
      - --diff
      - ./data
