name: Tapendium CI utils
description: CI utility functions
author: https://tapendium.com
requirements:
  - aws
  - jq
configuration:
  patternProperties:
    ^[a-z_]+$:
      type: object
      patternProperties:
        ^[a-z_]+$:
          anyOf:
            - type: string
            - type: boolean
            - type: number
      additionalProperties: false
      description: Arbitrary argument(s) required for utils
  additionalProperties: false
  properties: {}
